# Generated by Django 4.2.4 on 2024-04-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
